### ISSUE TITLE
KT on HTTP GET, POST, DELETE and PUT

### ISSUE THREAD

**Issue by pcyuen98** [pcyuen98/covidAngular#13]
GET and POST can do the most task. 

Research 3-5 reasons we need to have so many HTTP here?

**Comment by KahouTong** [comment]
- not only a simple and tidy way to expose objects to requests on the web but also  to **clarify the semantic differences**. Each operation is rather different. The point is to have nice HTTP methods that have clear, distinct meanings.
- **safety or idempotency**(can do it over and over again and it will always do exactly the same thing.) reasons, post are neither safe nor idempotent because may cause something different to happen each time
- replacing PUT/DELETE in favor of POST makes the API harder to read and PUT/DELETE calls are no longer idempotent.

Reference and for more details:
[https://stackoverflow.com/questions/147187/why-do-we-need-anything-more-than-http-get-put-post](url)

[https://www.artima.com/articles/why-put-and-delete](url)
