### ISSUE TITLE
Command on how to find files on linux. 

### ISSUE THREAD

**Issue by Devarajan222** [pcyuen98/covidAngular#23]
Creating file command
mkdir covid.log

![mkfile](https://user-images.githubusercontent.com/80657203/113553026-a4582e00-9629-11eb-84e1-df35391fe03d.PNG)

Search file command 
find . -name covid.log

![s1](https://user-images.githubusercontent.com/80657203/113553171-e6816f80-9629-11eb-96ea-1595d0f8c1e0.PNG)

Searching all file named Covid
find . -name '*Covid*'

![s2](https://user-images.githubusercontent.com/80657203/113553222-031da780-962a-11eb-9777-9db6cb2e8074.PNG)

Searching file based on Extension

find -name "*.js"

![s3](https://user-images.githubusercontent.com/80657203/113553662-b1295180-962a-11eb-963c-1dc042a644cc.PNG)

Link for online Linux environment 

https://bellard.org/jslinux/vm.html?url=buildroot-x86.cfg

Reference :
https://winaero.com/find-files-linux-terminal/

**Comment by pcyuen98** [comment]
when using find on windows it, has the issue below because windows has another "find" command.

"FIND: Parameter format not correct"

https://superuser.com/questions/126123/find-command-doesnt-seem-to-work-in-cygwin/126124

in order to use the CGYWIN, you may need to use exact path and filename - C:\opt>D:\cygwin64\bin\find . -name "*covid*"
