### ISSUE TITLE
KT - Practical 6  from Nurul to Deva

### ISSUE THREAD

**Issue by pcyuen98** [pcyuen98/covidAngular#7]
Provide Example what Class file can be autowired and what cannot be autowired.

**Comment by uyunAkmal** [comment]
The example for class file that can be @Autowired :
covidService, covidCasesRepository, covidCasesDescRepository, covidMiningAPITotalCases.

The file that cannot be  @Autowired :
CovidCaseDesc

Note: 
covidServiceImpl can be auto wired but auto wired should be interface only due to Java Abstraction concept.
