### ISSUE TITLE
KT - ORM and RDBMS

### ISSUE THREAD

**Issue by pcyuen98** [pcyuen98/covidAngular#9]
Please provide

What is ORM and RDBMS
https://www.h2kinfosys.com/blog/jdbc-vs-orm-framework/

3 Differences between ORM and RDBMS 

Reference link

**Comment by nrnh** [comment]
Object-Relational Mapping (ORM) is a software technique or library to create an abstraction between your code (or application) and the database.

Relational database management system (RDBMS) is a common type of database that stores data in tables and can handle complex queries.

Note: JDBC is not RDBMS. ORM  or Hibernate is another layer on top RDBMS. 

Differences:
1. ORM hide details of SQL queries from object-oriented logic so that we do not need to deal with database implementation. It makes CRUD implementation easier.
2. ORM allows you to switch database like from sql to oracle with minimal configuration changes instead of using native sql. For rdbms we will need to change the driver, dbms specific sql queries etc.
3. ORM is have slower performance than rdbms when dealing with large batch updates.

ref: 
https://www.quora.com/What-is-ORM-What-are-the-benefits-of-ORM
https://www.devteam.space/blog/hibernate-vs-jdbc-which-to-choose/#3
